version: '3'
services:
  container_dotnet:
    build: 
      context: ./dotnetapi/api-brick
      dockerfile: Dockerfile
    ports:
      - 82:80
    links:
      - container_database
    volumes:
      - /home/constructora-cluster/nodeapps/build-client/assets:/app/uploads
  container_node:
    build:
      context: ./nodeapps
      dockerfile: Dockerfile
    ports:
      - 81:8080
      - 83:8081
      - 86:8082
    volumes:
      - /home/constructora-cluster/nodeapps/build-admin/:/usr/src/app/build-admin
      - /home/constructora-cluster/nodeapps/build-client:/usr/src/app/build-client
      - /home/constructora-cluster/nodeapps/payment-simulator-mescyt:/usr/src/app/payment-simulator-mescyt

  container_database:
    image: mysql:5.7
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: brick

volumes:
  db_vol:
