version: '3'
services:
  container_dotnet:
    build: 
      context: ./dotnetapi/api-brick
      dockerfile: Dockerfile
    ports:
      - 82:80
    links:
      - container_database
  container_node:
    build:
      context: ./nodeapps
      dockerfile: Dockerfile
    ports:
      - 81:8080
      - 83:8081
    volumes:
      - /home/joshadow/development/constructora/nodeapps/build-admin/:/usr/src/app/build-admin
      - /home/joshadow/development/constructora/nodeapps/build-client/:/usr/src/app/build-client


  container_database:
    image: mysql:5.7
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: brick
    ports:
      - 3306:3306

volumes:
  db_vol:
